# Generated by Django 3.2.8 on 2022-11-23 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('profile_picture', models.ImageField(default='Null', null=True, upload_to='company/images/profile_picture', validators=[django.core.validators.validate_image_file_extension])),
                ('background_picture', models.ImageField(default='/image.png', null=True, upload_to='company/')),
                ('description', models.CharField(max_length=200, null=True)),
                ('forget_password_token', models.CharField(max_length=100, null=True)),
                ('email_verification_token', models.CharField(max_length=100, null=True)),
                ('email_status', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=True)),
                ('terms_and_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
