# Generated by Django 3.2.8 on 2022-11-28 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField()),
                ('scope_type', models.CharField(choices=[('WT', 'Website Testing'), ('AT', 'API Testing'), ('IS', 'iOS Application'), ('AD', 'Android Application'), ('IT', 'IoT Testing'), ('HT', 'Hardware Testing'), ('OT', 'Others')], default='OT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='out_scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_min', models.PositiveIntegerField()),
                ('p1_max', models.PositiveIntegerField()),
                ('p2_min', models.PositiveIntegerField()),
                ('p2_max', models.PositiveIntegerField()),
                ('p3_min', models.PositiveIntegerField()),
                ('p3_max', models.PositiveIntegerField()),
                ('p4_min', models.PositiveIntegerField()),
                ('p4_max', models.PositiveIntegerField()),
                ('p5_min', models.PositiveIntegerField()),
                ('p5_max', models.PositiveIntegerField()),
                ('max_reward', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('WT', 'Website Testing'), ('AT', 'API Testing'), ('IS', 'iOS Application'), ('AD', 'Android Application'), ('IT', 'IoT Testing'), ('HT', 'Hardware Testing'), ('OT', 'Others')], default='OT', max_length=2)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='companyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30)),
                ('title', models.CharField(blank=True, default='Company Name ', max_length=100)),
                ('introduction', models.TextField(blank=True, default='A bug bounty program', max_length=1000)),
                ('vulnerability_concerns', models.TextField(max_length=1000, null=True)),
                ('region', models.CharField(default='all', max_length=3)),
                ('visibility', models.CharField(choices=[('G', 'Global'), ('R', 'Regional'), ('P', 'Private')], default='G', max_length=1)),
                ('posted', models.BooleanField(default=False)),
                ('creation_step', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('in_scope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.in_scope')),
                ('out_scope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.out_scope')),
                ('rewards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.rewards')),
            ],
        ),
    ]
