# Generated by Django 3.2.8 on 2022-11-29 06:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0002_companyprogram_in_scope_out_scope_rewards_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=199)),
                ('report', models.FileField(upload_to='document/report', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('status', models.CharField(default='pending', max_length=50)),
                ('payment_status', models.BooleanField(default=False, null=True)),
                ('payment_amount', models.FloatField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.companyprogram')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
