# Generated by Django 3.2.8 on 2022-12-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0003_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.company')),
            ],
        ),
        migrations.CreateModel(
            name='company_login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='92.0.2.0')),
                ('old_ip_address', models.GenericIPAddressField(default='92.0.2.0')),
                ('old_login_time', models.DateTimeField()),
                ('new_login_time', models.DateTimeField(auto_now=True)),
                ('host_name', models.CharField(default='NULL', max_length=50)),
                ('old_host_name', models.CharField(default='NULL', max_length=50)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.company')),
            ],
        ),
    ]
