# Generated by Django 3.2.8 on 2022-12-26 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0004_company_login_details_company_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(choices=[('P1', 'P1 min - P1 max'), ('P2', 'P2 min - P2 max'), ('P3', 'P3 min - P3 max'), ('P4', 'P4 min - P4 max'), ('P5', 'P5 min - P5 max'), ('MR', 'Max Reward')], max_length=2)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.company')),
                ('transfer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
