# Generated by Django 3.2.8 on 2022-12-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0005_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='out_scope',
            old_name='target',
            new_name='out_target',
        ),
    ]
