# Generated by Django 3.2.8 on 2022-12-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0006_rename_target_out_scope_out_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprogram',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.company'),
        ),
    ]
