# Generated by Django 3.2.8 on 2022-12-28 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0007_alter_companyprogram_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprogram',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
