# Generated by Django 3.2.8 on 2022-12-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0008_alter_companyprogram_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprogram',
            old_name='company',
            new_name='company_id',
        ),
    ]
