# Generated by Django 3.2.8 on 2022-12-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0009_rename_company_companyprogram_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprogram',
            old_name='company_id',
            new_name='company',
        ),
    ]
