# Generated by Django 3.2.8 on 2023-01-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0011_alter_companyprogram_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprogram',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='in_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.in_scope'),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='out_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.out_scope'),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='rewards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.rewards'),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='vulnerability_concerns',
            field=models.TextField(max_length=1000),
        ),
    ]
