# Generated by Django 3.2.8 on 2023-01-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0012_auto_20230110_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='background_picture',
        ),
    ]
