# Generated by Django 3.2.8 on 2023-01-10 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0013_remove_company_background_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Null', null=True, upload_to='company/images/profile_picture', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
