# Generated by Django 3.2.8 on 2023-04-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0014_alter_company_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_wallet',
            name='description',
            field=models.CharField(default='description', max_length=40),
        ),
        migrations.AddField(
            model_name='company_wallet',
            name='status',
            field=models.CharField(choices=[('db', 'Debited'), ('cr', 'Credited')], default='none', max_length=3),
        ),
        migrations.AlterField(
            model_name='company_wallet',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.company'),
        ),
    ]
