# Generated by Django 3.2.8 on 2023-04-13 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0015_auto_20230413_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_wallet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company_wallet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company_wallet',
            name='status',
        ),
        migrations.AlterField(
            model_name='company_wallet',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.company'),
        ),
        migrations.CreateModel(
            name='company_wallet_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.CharField(default='description', max_length=40)),
                ('status', models.CharField(choices=[('db', 'Debited'), ('cr', 'Credited')], default='none', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.company')),
                ('recived_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
