# Generated by Django 3.2.8 on 2023-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0016_auto_20230413_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='in_scope',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='out_scope',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='rewards',
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='max_reward',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='out_target',
            field=models.URLField(default='http://test.com', null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p1_max',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p1_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p2_max',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p2_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p3_max',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p3_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p4_max',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p4_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p5_max',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='p5_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='scope_type',
            field=models.CharField(choices=[('WT', 'Website Testing'), ('AT', 'API Testing'), ('IS', 'iOS Application'), ('AD', 'Android Application'), ('IT', 'IoT Testing'), ('HT', 'Hardware Testing'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='target',
            field=models.URLField(default='http://test.com', null=True),
        ),
        migrations.DeleteModel(
            name='in_scope',
        ),
        migrations.DeleteModel(
            name='out_scope',
        ),
        migrations.DeleteModel(
            name='rewards',
        ),
    ]
