# Generated by Django 3.2.8 on 2023-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0017_auto_20230504_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprogram',
            name='creation_step',
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
