# Generated by Django 4.2.3 on 2023-08-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0019_private_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='private_invitation',
        ),
    ]
