# Generated by Django 4.2.2 on 2023-11-17 05:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0021_dropdownmenuoption_programcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 11, 17))]),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10),
        ),
    ]
