# Generated by Django 4.2.2 on 2023-11-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0022_companyprogram_expiry_date_companyprogram_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprogram',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
