# Generated by Django 4.2.2 on 2023-11-29 05:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0028_alter_companyprogram_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprogram',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='asset_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='asset_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='bounty',
            field=models.CharField(choices=[('Points', 'Points'), ('Rewards', 'Rewards')], default='Points', max_length=7),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='coverage',
            field=models.CharField(choices=[('Partial', 'Partial'), ('Full', 'Full')], default='Partial', max_length=7),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='max_severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='type',
            field=models.CharField(choices=[('Type1', 'Type 1'), ('Type2', 'Type 2')], default='Type1', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 11, 29))]),
        ),
    ]
