# Generated by Django 4.2.2 on 2023-12-04 08:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0029_remove_companyprogram_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprogram',
            name='coverage',
            field=models.CharField(choices=[('In Scope', 'In Scope'), ('Out of Scope', 'Out of Scope')], default='Partial', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 4))]),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='type',
            field=models.CharField(choices=[('Sourcecode', 'Sourcecode'), ('OtherAsset', 'OtherAsset'), ('AndroidApk', 'AndroidApk'), ('Wildcard', 'Wildcard'), ('Domain', 'Domain')], default='Type1', max_length=40),
        ),
    ]
