# Generated by Django 4.2.2 on 2023-12-08 06:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0031_alter_companyprogram_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='asset',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.CharField(max_length=199, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='impact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='severity',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='weakness',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 8))]),
        ),
    ]
