# Generated by Django 4.2.2 on 2023-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0032_submission_asset_submission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Critical', 'Critical')], max_length=10, null=True),
        ),
    ]
