# Generated by Django 4.2.2 on 2023-12-11 14:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0033_alter_submission_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprogram',
            name='policy',
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='scope_entries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='coverage',
            field=models.CharField(choices=[('Partial', 'Partial'), ('Full', 'Full')], default='Partial', max_length=7),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 11))]),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='title',
            field=models.CharField(blank=True, default='Company Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='type',
            field=models.CharField(choices=[('Type1', 'Type 1'), ('Type2', 'Type 2')], default='Type1', max_length=10),
        ),
    ]
