# Generated by Django 4.2.2 on 2023-12-17 15:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0035_alter_companyprogram_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprogram',
            name='asset_description',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='bounty',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='max_severity',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='scope_entries',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='type',
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 17))]),
        ),
        migrations.CreateModel(
            name='ScopeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, max_length=100)),
                ('asset_description', models.TextField(blank=True, max_length=1000)),
                ('type', models.CharField(choices=[('Sourcecode', 'Sourcecode'), ('OtherAsset', 'OtherAsset'), ('AndroidApk', 'AndroidApk'), ('Wildcard', 'Wildcard'), ('Domain', 'Domain')], default='Type1', max_length=10)),
                ('coverage', models.CharField(choices=[('In Scope', 'In Scope'), ('Out of Scope', 'Out of Scope')], default='Partial', max_length=27)),
                ('max_severity', models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('bounty', models.CharField(choices=[('Points', 'Points'), ('Rewards', 'Rewards')], default='Points', max_length=7)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_entries', to='CompanyApi.companyprogram')),
            ],
        ),
    ]
