# Generated by Django 4.2.2 on 2023-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0036_remove_companyprogram_asset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprogram',
            name='policy',
            field=models.TextField(null=True),
        ),
    ]
