# Generated by Django 4.2.2 on 2023-12-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0037_companyprogram_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeentry',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
