# Generated by Django 4.2.2 on 2023-12-26 09:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0038_scopeentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 26))]),
        ),
    ]
