# Generated by Django 4.2.2 on 2023-12-28 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0040_alter_companyprogram_expiry_date_companywallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companywallet',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_personal_wallet', to='CompanyApi.company'),
        ),
    ]
