# Generated by Django 4.2.2 on 2023-12-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0041_alter_company_company_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankdetail',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_details', to='CompanyApi.company'),
        ),
    ]
