# Generated by Django 4.2.2 on 2023-12-29 05:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0042_alter_companybankdetail_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankdetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_details', to='CompanyApi.company'),
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 29))]),
        ),
    ]
