# Generated by Django 4.2.2 on 2023-12-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0043_alter_companybankdetail_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companywallet',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
