# Generated by Django 4.2.2 on 2023-12-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0044_companywallet_stripe_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetail',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companywallet',
            name='stripe_account_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companybankdetail',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_details', to='CompanyApi.company'),
        ),
        migrations.AlterField(
            model_name='companywallet',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_personal_wallet', to='CompanyApi.company'),
        ),
    ]
