# Generated by Django 4.2.2 on 2023-12-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0045_companybankdetail_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankdetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_details', to='CompanyApi.company'),
        ),
    ]
