# Generated by Django 4.2.2 on 2024-01-08 08:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0046_alter_companybankdetail_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 1, 8))]),
        ),
    ]
