# Generated by Django 4.2.2 on 2024-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0052_alter_companyprogram_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprogram',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_profiles/'),
        ),
    ]
