# Generated by Django 4.2.2 on 2024-01-29 09:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0053_companyprogram_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 1, 29))]),
        ),
    ]
