# Generated by Django 4.2.2 on 2024-04-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0057_alter_companyprogram_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprogram',
            name='profile_image',
        ),
    ]
