# Generated by Django 4.2.2 on 2024-04-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0058_remove_companyprogram_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprogram',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_profiles/'),
        ),
    ]
