# Generated by Django 4.2.2 on 2024-04-25 21:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0059_companyprogram_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companywallet',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='companywallet',
            name='stripe_transaction_id',
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 25))]),
        ),
    ]
