# Generated by Django 4.2.2 on 2024-05-02 07:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0060_remove_companywallet_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_wallet_history',
            name='recived_from',
        ),
        migrations.AlterField(
            model_name='companyprogram',
            name='expiry_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 5, 2))]),
        ),
    ]
