# Generated by Django 4.2.2 on 2024-05-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0062_company_razorpay_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_razorpay_account',
        ),
    ]
