# Generated by Django 4.2.2 on 2024-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0065_delete_company_razorpay_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_razorpay_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
