# Generated by Django 4.2.2 on 2024-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0066_company_razorpay_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_razorpay_account',
            name='acc_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
