# Generated by Django 4.2.2 on 2024-05-02 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0067_alter_company_razorpay_account_acc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_razorpay_account',
            name='acc_id',
        ),
        migrations.AddField(
            model_name='company_razorpay_account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
