# Generated by Django 4.2.2 on 2024-05-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0068_remove_company_razorpay_account_acc_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_razorpay_account',
        ),
    ]
