# Generated by Django 4.2.2 on 2024-05-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0070_company_razorpay_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_razorpay_account',
            name='user',
        ),
        migrations.AddField(
            model_name='company_razorpay_account',
            name='acc_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company_razorpay_account',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.company'),
        ),
    ]
