from django.urls import path
from . import views
from .views import YourView,CreateAccount,FundAccounts

urlpatterns = [
    path('register/',views.ProfessionalRegisterAPIView.as_view()),
    path('dashboard/',views.ProfessionalDashboardAPIView.as_view()),
    path('programs/',views.ProfessionalProgramAPIView.as_view()),
    path('program/details/<int:pk>',views.ProfessionalProgramDetailsAPIView.as_view()),
    path('submission/', views.ProfessionalSubmissionAPIView.as_view(),name='submission-details'),
    path('professionals/<int:pk>/update_invitation_preference/', views.UpdateInvitationPreferenceAPIView.as_view(), name='professional-update-invitation-preference'),
    path('professionals/filter_by_invitation_preference/', views.FilterProfessionalsByInvitationPreferenceAPIView.as_view(), name='professional-filter-by-invitation-preference'),
    path('submission-details/', views.ProfessionalSubmissionDetailsAPIView.as_view(), name='submission-details'),
    path('submission/details/<int:pk>',views.ProfessionalSubmissionDetailsAPIView.as_view()),
    path('leaderboard/',views.ProfessionalLearderAPIView.as_view()),
    path('remove_user_from_leaderboard/', views.RemoveUserFromLeaderboardAPIView.as_view(), name='remove_user_from_leaderboard'),
    path('leaderboard/details/<int:pk>',views.ProfessionalLeaderDetailsAPIView.as_view()),
    path('setting/',views.ProfessionalSettingsAPIView.as_view()),
    path('settings/changename/',views.ProfessionalSettingsNameDescriptionAPIView.as_view()),
    path('settings/changeusername/',views.ProfessionalSettingsUserEmailAPIView.as_view()),
    path('settings/changepassword/',views.ProfessionalSettingsUpdatePasswordAPIView.as_view()),
    path('settings/skill/', views.ProfessionalSettingsSkillsAPIView.as_view(),
         name='settings-skill'),
    path('settings/skill/<int:pk>',views.ProfessionalDeleteSkillAPIView.as_view()),
    path('settings/uploadimage/',views.ProfessionalSettingsUploadPictureAPIView.as_view()),
    path('settings/resume/',views.ProfessionalSettingsUploadResumeAPIView.as_view()),
    # path('settings/optionalemail/',views.ProfessionalSettingsOptionalEmailAPIView.as_view()),
    path('favourite/',views.ProfessionalFavouriteListAPIView.as_view()),
    path('favourite/<int:pk>',views.PrefessionalFavouritePorgramAPIView.as_view()),
    path('information/',views.ProfessionalInformationAPIView.as_view()),
    path('withdraw/',views.ProfessionalPaymentAPIView.as_view()),
    path('test',views.ProfessionalTestAPIView.as_view()),
    path('test_update',views.ProfessionalTestUpdateAPIView.as_view()),
    path('upload/', views.ResumeUploadAPIView.as_view(), name='resume-upload'),
    path('delete/<int:resume_id>/', views.ResumeDeleteAPIView.as_view(), name='resume-delete'),
    # path('quiz/', views.QuizAPIView.as_view(), name='quiz-api'),
    path('deactivate_account/', views.DeactivateAccountAPIView.as_view(), name='deactivate_account'),
    path('add_certification/', views.CertificationAPIView.as_view(), name='add_certification'),
    path('certificates/', views.ListCertificatesAPIView.as_view(), name='list_certificates'),
    path('certificates/delete/<int:certificate_id>/', views.DeleteCertificateAPIView.as_view(), name='delete_certificate'),
    path('certificates/update/<int:certificate_id>/', views.UpdateCertificateAPIView.as_view(), name='update_certificate'),
    path('follow/', views.FollowProfessionalAPIView.as_view(), name='follow-professional'),
    path('unfollow/', views.UnfollowProfessionalAPIView.as_view(), name='unfollow-professional'),
    path('follower/<int:follower_id>/', views.FollowerProfileAPIView.as_view(), name='follower-profile'),
    path('followed-user/<int:followed_id>/', views.FollowedUserProfileAPIView.as_view(), name='followed-user-profile'),
    path('followers-list/', views.FollowersListAPIView.as_view(), name='followers-list'),
    path('following-list/', views.FollowingListAPIView.as_view(), name='following-list'),
    path('update-profile/', views.UpdateUserProfileAndProfessional.as_view(), name='update-profile'),
    path('get-updated-profile/', views.GetUpdatedUserProfileAndProfessional.as_view(), name='get-updated-profile'),
    path('search-user/<str:username>/', views.SearchUserByUsername.as_view(), name='search-user-by-username'),
    path('quiz/', YourView.as_view(), name='user-selection'),
    path('user-selection-update/<int:pk>/',
         views.UserSelectionUpdateView.as_view(), name='user-selection-update'),
    # path('api/get-user-responses/', views.GetUserResponsesAPIView.as_view(), name='get-user-responses'),
    path('companies/', views.UnifiedCompanyAPIView.as_view(), name='companies'),
    path('api/programs/', views.CompanyProgramListAPIView.as_view(), name='program-list'),
    path('user-profile-details/<int:user_id>/', views.UserProfileDetailsAPIView.as_view(), name='user_profile_details_api'),
    path('bank-detail/create/', views.ProfessionalBankDetailCreateView.as_view(), name='professional-bank-detail-create'),
    path('bank-detail/retrieve/', views.ProfessionalBankDetailRetrieveView.as_view(), name='professional-bank-detail-retrieve'),
    path('withdraw-money-from-wallet/', views.WithdrawMoneyFromWalletView.as_view(), name='withdraw-money-from-wallet'),
    path('wallet/', views.WalletBalanceView.as_view(), name='wallet-balance'),
#     path('streak/', views.StreakAPIView.as_view(), name='streak-api'),
    path('stripeCreateAccountSession/', views.StripeConnectCreateAccountSessionView.as_view(), name='stripeconnect-accountsession'),
#     path('stripeConnectCreateAccount/', views.StripeConnectCreateAccount.as_view(), name='stripeconnect-createaccount-api'),
    path('custom-scope-entries/<int:program_id>/',
         views.CustomScopeEntryListCreateView.as_view(), name='custom-scope-entry-list'),
    path('program/<int:pk>/', views.CompanyProgramDetailsAPIViewinProfessional.as_view(),
         name='company-program-details -in_professional'),
#     path('stripeaccountget/<str:pk>/', views.StripeConnectAccountRetrieve.as_view(),
#          name='stripeaccountget'),
    path('stripeaccountupdate/<str:pk>/', views.StripeAccUpdate.as_view(),
         name='stripeaccountupdate'),
#     path('api/calculate_streak/<int:user_id>/',
#          views.CalculateStreakAPIView.as_view(), name='calculate_streak'),
#     path('api/award-streak-badges/<int:user_id>/',
#          views.AwardStreakBadgesAPIView.as_view(), name='award_streak_badges_api')
    path("razorpay/account/create",
         CreateAccount.as_view(),
         name="razorpay-create-account-api"
         ),

    path("razorpay/accounts/",
         FundAccounts.as_view(),
         name="razorpay-fund-account-api"
         ),
]
