# Generated by Django 3.2.8 on 2022-12-03 05:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApi', '0003_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True)),
                ('profile_picture', models.ImageField(blank=True, default='Null', null=True, upload_to='student/images/profile_picture', validators=[django.core.validators.validate_image_file_extension])),
                ('resume', models.FileField(blank=True, default='Null', null=True, upload_to='student/document/resume', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('profile_description', models.CharField(max_length=60, null=True)),
                ('forget_password_token', models.CharField(max_length=100, null=True)),
                ('email_verification_token', models.CharField(max_length=100, null=True)),
                ('email_status', models.BooleanField(default=False)),
                ('reward', models.BigIntegerField(default=10)),
                ('interst', models.CharField(max_length=40, null=True)),
                ('visibility', models.BooleanField(default=False)),
                ('terms_and_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_wallet_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('db', 'Debited'), ('cr', 'Credited')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApi.student')),
            ],
        ),
        migrations.CreateModel(
            name='student_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentApi.student')),
            ],
        ),
        migrations.CreateModel(
            name='student_login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('old_ip_address', models.GenericIPAddressField()),
                ('old_login_time', models.DateTimeField()),
                ('new_login_time', models.DateTimeField(auto_now=True)),
                ('host_name', models.CharField(default='NULL', max_length=50)),
                ('old_host_name', models.CharField(default='NULL', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentApi.student')),
            ],
        ),
        migrations.CreateModel(
            name='student_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_names', models.CharField(choices=[('inr', 'India'), ('aud', 'Australia')], max_length=3)),
                ('college_name', models.CharField(max_length=50)),
                ('college_id', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentApi.student')),
            ],
        ),
        migrations.CreateModel(
            name='student_favourite_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.companyprogram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApi.student')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
