# Generated by Django 3.2.8 on 2022-12-07 12:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyApi', '0004_company_login_details_company_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True)),
                ('profile_picture', models.ImageField(blank=True, default='Null', null=True, upload_to='professional/images/profile_picture', validators=[django.core.validators.validate_image_file_extension])),
                ('profile_description', models.CharField(max_length=60, null=True)),
                ('resume', models.FileField(blank=True, default='Null', null=True, upload_to='professional/document/resume', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('reward', models.BigIntegerField(default=10)),
                ('forget_password_token', models.CharField(max_length=100, null=True)),
                ('optional_email', models.EmailField(max_length=254)),
                ('email_verification_token', models.CharField(max_length=100, null=True)),
                ('email_status', models.BooleanField(default=False)),
                ('interst', models.CharField(max_length=40, null=True)),
                ('terms_and_policy', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='professional_wallet_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('db', 'Debited'), ('cr', 'Credited')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
            ],
        ),
        migrations.CreateModel(
            name='professional_wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
            ],
        ),
        migrations.CreateModel(
            name='professional_socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('links', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='professional_login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='92.0.2.0')),
                ('old_ip_address', models.GenericIPAddressField(default='92.0.2.0')),
                ('old_login_time', models.DateTimeField()),
                ('new_login_time', models.DateTimeField(auto_now=True)),
                ('host_name', models.CharField(default='NULL', max_length=50)),
                ('old_host_name', models.CharField(default='NULL', max_length=50)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
            ],
        ),
        migrations.CreateModel(
            name='professional_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_names', models.CharField(choices=[('inr', 'India'), ('aud', 'Australia')], max_length=3)),
                ('status', models.BooleanField(default=False)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
            ],
        ),
        migrations.CreateModel(
            name='professional_favourite_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.companyprogram')),
            ],
        ),
    ]
