# Generated by Django 3.2.8 on 2022-12-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='professional_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
            ],
        ),
    ]
