# Generated by Django 3.2.8 on 2022-12-29 04:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0010_rename_company_id_companyprogram_company'),
        ('ProfessionalApi', '0002_professional_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='professional_program_submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.FileField(blank=True, default='Null', null=True, upload_to='professional/document/submission', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.companyprogram')),
            ],
        ),
    ]
