# Generated by Django 3.2.8 on 2022-12-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0003_professional_program_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='professional_program_submission',
        ),
    ]
