# Generated by Django 4.2.3 on 2023-08-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApi', '0020_delete_private_invitation'),
        ('ProfessionalApi', '0008_alter_professional_professional_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='private_invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApi.companyprogram')),
            ],
        ),
    ]
