# Generated by Django 4.2.2 on 2023-11-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0012_quizquestion_resumemodel_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('organisations', models.CharField(max_length=255)),
                ('issues_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('certificate_date', models.DateField()),
                ('certificate_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='professional',
            name='invitation_preference',
            field=models.BooleanField(default=True),
        ),
    ]
