# Generated by Django 4.2.2 on 2023-11-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0013_certificate_professional_invitation_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_date',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
