# Generated by Django 4.2.2 on 2023-11-17 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0014_remove_certificate_certificate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
