# Generated by Django 4.2.2 on 2023-11-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0016_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='optional_email',
        ),
    ]
