# Generated by Django 4.2.2 on 2023-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0017_remove_professional_optional_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='optional_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
