# Generated by Django 4.2.2 on 2023-11-21 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfessionalApi', '0018_professional_optional_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('bugcrowd_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('cobalt_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('hack_the_box_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default_profile_picture.png', null=True, upload_to='user_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
