# Generated by Django 4.2.2 on 2023-11-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0020_professional_about_me_professional_bugcrowd_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='employment_type',
            field=models.CharField(default='open_for_employemnt', max_length=40),
        ),
    ]
