# Generated by Django 4.2.2 on 2023-11-27 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfessionalApi', '0021_professional_employment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(choices=[('CTF', 'CTF'), ('VDP', 'VDP'), ('BBP', 'BBP'), ('Challenge', 'Challenge'), ('pentest', 'pentest')], max_length=10)),
                ('question_2', models.CharField(choices=[('Novice', 'Novice'), ('Starter', 'Starter'), ('Advanced', 'Advanced'), ('Expert', 'Expert'), ('Legend', 'Legend')], max_length=10)),
                ('question_3', models.CharField(choices=[('DOMAIN', 'DOMAIN'), ('URL', 'URL'), ('IP ADDRESS', 'IP ADDRESS'), ('CIDR', 'CIDR'), ('IOS:APP STORE', 'IOS:APP STORE'), ('IOS TESTFLIGHT', 'IOS TESTFLIGHT'), ('IOS:IPA', 'IOS:IPA'), ('ANDROID PLAYSTORE', 'ANDROID PLAYSTORE'), ('ANDROID APK', 'ANDROID APK'), ('WINDOWS:MICROSOFT STORE', 'WINDOWS:MICROSOFT STORE'), ('SOURCE CODE', 'SOURCE CODE'), ('EXECUTABLE', 'EXECUTABLE'), ('HARDWARE:IOT', 'HARDWARE:IOT'), ('SMART CONTRACT', 'SMART CONTRACT'), ('WILDCARD', 'WILDCARD')], max_length=50)),
                ('question_4', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Occasionally', 'Occasionally')], max_length=20)),
                ('question_5', multiselectfield.db.fields.MultiSelectField(choices=[('information_disclosure', 'Information Disclosure'), ('improper_authentication_generic', 'Improper Authentication - Generic'), ('cross_site_scripting_reflected', 'Cross-Site Scripting (XSS) - Reflected'), ('violation_secure_design_principles', 'Violation of Secure Design Principles'), ('improper_access_control_generics', 'Improper Access Control - Generics'), ('cross_site_scripting_generics', 'Cross-Site Scripting (XSS) - Generics'), ('cross_site_request_forgery', 'Cross-Site Request Forgery (CSRF)'), ('open_redirect', 'Open Redirect'), ('cross_site_scripting_stored', 'Cross-Site Scripting (XSS) - Stored'), ('privilege_escalation', 'Privilege Escalation')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
