# Generated by Django 4.2.2 on 2023-11-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0022_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
    ]
