# Generated by Django 4.2.2 on 2023-12-04 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfessionalApi', '0023_remove_userresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question_1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CTF', 'CTF'), ('VDP', 'VDP'), ('BBP', 'BBP'), ('Challenge', 'Challenge'), ('pentest', 'pentest')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question_3',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DOMAIN', 'DOMAIN'), ('URL', 'URL'), ('IP ADDRESS', 'IP ADDRESS'), ('CIDR', 'CIDR'), ('IOS:APP STORE', 'IOS:APP STORE'), ('IOS TESTFLIGHT', 'IOS TESTFLIGHT'), ('IOS:IPA', 'IOS:IPA'), ('ANDROID PLAYSTORE', 'ANDROID PLAYSTORE'), ('ANDROID APK', 'ANDROID APK'), ('WINDOWS:MICROSOFT STORE', 'WINDOWS:MICROSOFT STORE'), ('SOURCE CODE', 'SOURCE CODE'), ('EXECUTABLE', 'EXECUTABLE'), ('HARDWARE:IOT', 'HARDWARE:IOT'), ('SMART CONTRACT', 'SMART CONTRACT'), ('WILDCARD', 'WILDCARD')], max_length=50),
        ),
    ]
