# Generated by Django 4.2.2 on 2023-12-04 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfessionalApi', '0024_userresponse_user_alter_userresponse_question_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
