# Generated by Django 4.2.2 on 2023-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0025_alter_userresponse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='question_1',
            field=models.CharField(choices=[('CTF', 'CTF'), ('VDP', 'VDP'), ('BBP', 'BBP'), ('Challenge', 'Challenge'), ('pentest', 'pentest')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question_3',
            field=models.CharField(choices=[('DOMAIN', 'DOMAIN'), ('URL', 'URL'), ('IP ADDRESS', 'IP ADDRESS'), ('CIDR', 'CIDR'), ('IOS:APP STORE', 'IOS:APP STORE'), ('IOS TESTFLIGHT', 'IOS TESTFLIGHT'), ('IOS:IPA', 'IOS:IPA'), ('ANDROID PLAYSTORE', 'ANDROID PLAYSTORE'), ('ANDROID APK', 'ANDROID APK'), ('WINDOWS:MICROSOFT STORE', 'WINDOWS:MICROSOFT STORE'), ('SOURCE CODE', 'SOURCE CODE'), ('EXECUTABLE', 'EXECUTABLE'), ('HARDWARE:IOT', 'HARDWARE:IOT'), ('SMART CONTRACT', 'SMART CONTRACT'), ('WILDCARD', 'WILDCARD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question_5',
            field=models.CharField(choices=[('information_disclosure', 'Information Disclosure'), ('improper_authentication_generic', 'Improper Authentication - Generic'), ('cross_site_scripting_reflected', 'Cross-Site Scripting (XSS) - Reflected'), ('violation_secure_design_principles', 'Violation of Secure Design Principles'), ('improper_access_control_generics', 'Improper Access Control - Generics'), ('cross_site_scripting_generics', 'Cross-Site Scripting (XSS) - Generics'), ('cross_site_request_forgery', 'Cross-Site Request Forgery (CSRF)'), ('open_redirect', 'Open Redirect'), ('cross_site_scripting_stored', 'Cross-Site Scripting (XSS) - Stored'), ('privilege_escalation', 'Privilege Escalation')], max_length=100),
        ),
    ]
