# Generated by Django 4.2.2 on 2023-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0026_alter_userresponse_question_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('CTF', 'CTF'), ('VDP', 'Vulnerability Detection and Penetration Testing'), ('BBP', 'Bug Bounty Program'), ('Challenge', 'Challenge'), ('pentest', 'Penetration Testing')], max_length=255)),
                ('q2', models.CharField(choices=[('Novice', 'Novice'), ('Starter', 'Starter'), ('Advanced', 'Advanced'), ('Expert', 'Expert'), ('Legend', 'Legend')], max_length=255)),
                ('q3', models.CharField(choices=[('DOMAIN', 'Domain'), ('URL', 'URL'), ('IP_ADDRESS', 'IP Address'), ('CIDR', 'CIDR'), ('IOS:APP_STORE', 'iOS App Store'), ('IOS_TESTFLIGHT', 'iOS TestFlight'), ('IOS:IPA', 'iOS IPA'), ('ANDROID_PLAYSTORE', 'Android PlayStore'), ('ANDROID_APK', 'Android APK'), ('WINDOWS:MICROSOFT_STORE', 'Windows Microsoft Store'), ('SOURCE_CODE', 'Source Code'), ('EXECUTABLE', 'Executable'), ('HARDWARE:IOT', 'Hardware: Internet of Things'), ('SMART_CONTRACT', 'Smart Contract'), ('WILDCARD', 'Wildcard')], max_length=255)),
                ('q4', models.CharField(choices=[('Full time', 'Full Time'), ('Part time', 'Part Time'), ('Occasionally', 'Occasionally')], max_length=255)),
                ('q5', models.CharField(choices=[('information_disclosure', 'Information Disclosure'), ('improper_authentication_generic', 'Improper Authentication (Generic)'), ('cross_site_scripting_reflected', 'Cross-Site Scripting (Reflected)'), ('violation_secure_design_principles', 'Violation of Secure Design Principles'), ('improper_access_control_generics', 'Improper Access Control (Generic)'), ('cross_site_scripting_generics', 'Cross-Site Scripting (Generic)'), ('cross_site_request_forgery', 'Cross-Site Request Forgery'), ('open_redirect', 'Open Redirect'), ('cross_site_scripting_stored', 'Cross-Site Scripting (Stored)'), ('privilege_escalation', 'Privilege Escalation')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('q1__gte', 1), ('q1__lte', 3)), name='q1'),
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('q3__gte', 1), ('q3__lte', 3)), name='q3'),
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('q5__gte', 1), ('q5__lte', 3)), name='q5'),
        ),
    ]
