# Generated by Django 4.2.2 on 2023-12-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0027_userselection_delete_userresponse_userselection_q1_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userselection',
            name='q1',
        ),
        migrations.RemoveConstraint(
            model_name='userselection',
            name='q3',
        ),
        migrations.RemoveConstraint(
            model_name='userselection',
            name='q5',
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('q1__gte', 1), ('q1__lte', 3)), name='check_q1'),
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('q3__gte', 1), ('q3__lte', 3)), name='check_q3'),
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('q5__gte', 1), ('q5__lte', 3)), name='check_q5'),
        ),
    ]
