# Generated by Django 4.2.2 on 2023-12-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0028_remove_userselection_q1_remove_userselection_q3_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userselection',
            name='check_q1',
        ),
        migrations.RemoveConstraint(
            model_name='userselection',
            name='check_q3',
        ),
        migrations.RemoveConstraint(
            model_name='userselection',
            name='check_q5',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q1',
            new_name='question_1',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q2',
            new_name='question_2',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q3',
            new_name='question_3',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q4',
            new_name='question_4',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q5',
            new_name='question_5',
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('question_1__gte', 1), ('question_1__lte', 3)), name='check_question_1'),
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('question_3__gte', 1), ('question_3__lte', 3)), name='check_question_3'),
        ),
        migrations.AddConstraint(
            model_name='userselection',
            constraint=models.CheckConstraint(check=models.Q(('question_5__gte', 1), ('question_5__lte', 3)), name='check_question_5'),
        ),
    ]
