# Generated by Django 4.2.2 on 2023-12-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0029_remove_userselection_check_q1_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userselection',
            name='check_question_1',
        ),
        migrations.RemoveConstraint(
            model_name='userselection',
            name='check_question_3',
        ),
        migrations.RemoveConstraint(
            model_name='userselection',
            name='check_question_5',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='question_3',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='question_4',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='question_5',
        ),
        migrations.AddField(
            model_name='userselection',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
