# Generated by Django 4.2.2 on 2023-12-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0030_remove_userselection_check_question_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselection',
            old_name='data',
            new_name='q1',
        ),
        migrations.AddField(
            model_name='userselection',
            name='q2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userselection',
            name='q3',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userselection',
            name='q4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userselection',
            name='q5',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='ProfessionalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='ProfessionalApi.professional')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='ProfessionalApi.professional')),
            ],
        ),
    ]
