# Generated by Django 4.2.2 on 2023-12-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0031_rename_data_userselection_q1_userselection_q2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselection',
            old_name='q1',
            new_name='question_1',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q2',
            new_name='question_2',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q3',
            new_name='question_3',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q4',
            new_name='question_4',
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='q5',
            new_name='question_5',
        ),
    ]
