# Generated by Django 4.2.2 on 2023-12-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0032_rename_q1_userselection_question_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalwallet',
            name='professional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='ProfessionalApi.professional'),
        ),
    ]
