# Generated by Django 4.2.2 on 2024-01-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0035_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='questions_completed',
            field=models.BooleanField(default=False),
        ),
    ]
