# Generated by Django 4.2.2 on 2024-01-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0036_professional_questions_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz', to='ProfessionalApi.professional'),
        ),
    ]
