# Generated by Django 4.2.2 on 2024-04-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0039_badge_streak_badgeaward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeaward',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='badgeaward',
            name='user',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='BadgeAward',
        ),
        migrations.DeleteModel(
            name='streak',
        ),
    ]
