# Generated by Django 4.2.2 on 2024-05-02 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfessionalApi', '0040_remove_badgeaward_badge_remove_badgeaward_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_wallet_history',
            name='recived_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
