# Generated by Django 4.2.2 on 2024-05-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApi', '0041_professional_wallet_history_recived_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='professional_razorpay_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=30, null=True, unique=True)),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfessionalApi.professional')),
            ],
        ),
    ]
