# Generated by Django 3.2.8 on 2022-12-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('text', models.CharField(max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
