# Generated by Django 3.2.8 on 2023-02-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatenumber',
            name='code',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='validatenumber',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
