# Generated by Django 3.2.8 on 2023-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0003_auto_20230222_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='optional_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
